### ISSUE TITLE
Really helpful! But I encountered error when index over 46MB

### ISSUE THREAD

**Issue by hxsmyxh** [robindekoster/chatgpt-custom-knowledge-chatbot#1]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/29764552/232736835-663eed83-59d6-4c6f-9f39-7906fe819f4c.png">

As shown here, I can't input any prompt.

Besides, could it also recognise the excel/word/notion file?

**Comment by robindekoster** [comment]
Hey, I'm glad this repo is helpful for you!

I think your index (knowledge base) is too big. The text-davinci-003 model (which this script uses by default) has a maximum token length of 4097, seems like more people have [the same problem](https://github.com/jerryjliu/llama_index/issues/294) (maybe you can make the workaround work).

With a little modification it should be able to parse a lot of file types including Notion, csv and docs see [this link](https://llamahub.ai/) for all loaders.
